# Generated by Django 3.1.6 on 2021-02-26 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travelapp', '0001_initial'),
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_size', models.IntegerField(default=1, verbose_name='Размер вашей группы')),
                ('options_used', models.ManyToManyField(to='travelapp.TripOptionAvailable', verbose_name='Дополнительные опции')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_trips', to='authapp.traveler')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered', to='travelapp.trip', verbose_name='Поход')),
            ],
            options={
                'unique_together': {('traveler', 'trip')},
            },
        ),
    ]
