# Generated by Django 3.1.6 on 2021-02-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0017_auto_20210222_1249'),
        ('ordersapp', '0004_auto_20210222_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='options_used',
            field=models.ManyToManyField(null=True, to='travelapp.TripOptionAvailable', verbose_name='Дополнительные опции'),
        ),
    ]
