# Generated by Django 3.1.6 on 2021-02-22 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0017_auto_20210222_1249'),
        ('authapp', '0006_auto_20210222_1550'),
        ('ordersapp', '0005_auto_20210222_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='traveler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_trips', to='authapp.traveler'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered', to='travelapp.trip', verbose_name='Поход'),
        ),
    ]
