# Generated by Django 3.1.6 on 2021-02-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='home_region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Место проживания'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='routes_run',
            field=models.IntegerField(default=0, verbose_name='Пройдено маршрутов'),
        ),
        migrations.AlterField(
            model_name='route',
            name='complexity',
            field=models.IntegerField(choices=[(1, 'Простой'), (2, 'Продвинутый'), (3, 'Сложный')], db_index=True, default=1, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='route',
            name='featured_photo',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Фото для оформления маршрута'),
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО пользователя')),
                ('about', models.TextField(blank=True, verbose_name='О себе')),
                ('home_region', models.CharField(max_length=100, verbose_name='Место проживания')),
                ('routes_run', models.IntegerField(default=0, verbose_name='Пройдено маршрутов')),
                ('subscribed_to', models.ManyToManyField(to='travelapp.Instructor', verbose_name='Подписки')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='subscribers',
            field=models.ManyToManyField(to='travelapp.Traveler', verbose_name='Подписчики'),
        ),
    ]
