# Generated by Django 3.1.6 on 2021-02-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_instructor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='subscribers',
            field=models.ManyToManyField(blank=True, to='travelapp.Traveler', verbose_name='Подписчики'),
        ),
    ]
