# Generated by Django 3.1.6 on 2021-02-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_auto_20210208_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='traveler',
            name='subscribed_to',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='travelapp.Instructor', verbose_name='Подписки'),
        ),
    ]
