# Generated by Django 3.1.6 on 2021-02-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0009_auto_20210216_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='type',
            field=models.IntegerField(choices=[(1, 'Пеший'), (2, 'Велосипедный'), (3, 'Водный')], db_index=True, default=1, verbose_name='Тип маршрута'),
        ),
    ]
