# Generated by Django 3.1.6 on 2021-02-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0012_trip_subbed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='base_price_currency',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='route',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Ориентировочная стоимость прохождения маршрута'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость прохождения маршрута'),
        ),
        migrations.CreateModel(
            name='TripOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование опции')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Стоимость опции')),
                ('trip', models.ManyToManyField(related_name='options', to='travelapp.Trip')),
            ],
        ),
    ]
