# Generated by Django 3.1.6 on 2021-02-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0013_auto_20210221_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ориентировочная стоимость прохождения маршрута'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость прохождения маршрута'),
        ),
        migrations.AlterField(
            model_name='tripoption',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Стоимость опции'),
        ),
    ]
