# Generated by Django 3.1.6 on 2021-02-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0014_auto_20210221_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripoption',
            name='name',
            field=models.IntegerField(choices=[(1, 'Страховка'), (2, 'Аренда инвентаря'), (3, 'Питание'), (4, 'Проживание'), (5, 'Проезд до места')], verbose_name='Наименование опции'),
        ),
    ]
