# Generated by Django 3.1.6 on 2021-02-21 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
        ('travelapp', '0015_auto_20210221_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='authapp.instructor'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='authapp.instructor'),
        ),
    ]
