# Generated by Django 3.1.6 on 2021-02-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0017_auto_20210222_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='group_size',
            new_name='max_group_size',
        ),
    ]
