# Generated by Django 3.1.6 on 2021-02-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0018_auto_20210222_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routephoto',
            name='image',
            field=models.ImageField(upload_to='static/route_photos'),
        ),
    ]
