# Generated by Django 3.1.6 on 2021-02-26 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Наименование')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.district')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название маршрута')),
                ('type', models.IntegerField(choices=[(1, 'Пеший'), (2, 'Велосипедный'), (3, 'Водный')], db_index=True, default=1, verbose_name='Тип маршрута')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ориентировочная стоимость прохождения маршрута')),
                ('short_desc', models.TextField(verbose_name='Краткое описание')),
                ('long_desc', models.TextField(verbose_name='Полное описание')),
                ('duration', models.IntegerField(db_index=True, verbose_name='Продолжительность')),
                ('length', models.FloatField(db_index=True, verbose_name='Длина')),
                ('complexity', models.IntegerField(choices=[(1, 'Простой'), (2, 'Продвинутый'), (3, 'Сложный')], db_index=True, default=1, verbose_name='Сложность')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания маршрута')),
                ('featured_photo', models.ImageField(blank=True, upload_to='static/img', verbose_name='Фото для оформления маршрута')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Маршрут доступен для проведения')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='authapp.instructor')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travelapp.region', verbose_name='Местоположение')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость прохождения маршрута')),
                ('announced_at', models.DateTimeField(auto_now_add=True, verbose_name='Время объявления похода')),
                ('starts_at', models.DateTimeField(verbose_name='Время начала похода')),
                ('subbed', models.IntegerField(default=0, verbose_name='Мест занято')),
                ('max_group_size', models.IntegerField(null=True, verbose_name='Количество мест')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='authapp.instructor')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='travelapp.route')),
            ],
        ),
        migrations.CreateModel(
            name='TripOptionAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'Страховка'), (2, 'Аренда инвентаря'), (3, 'Питание'), (4, 'Проживание'), (5, 'Проезд до места')], verbose_name='Наименование опции')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Стоимость опции')),
                ('trip', models.ManyToManyField(related_name='options', to='travelapp.Trip')),
            ],
        ),
        migrations.CreateModel(
            name='RoutePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/route_photos')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='travelapp.route')),
            ],
        ),
    ]
