# Generated by Django 3.1.6 on 2021-02-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='subbed',
        ),
        migrations.AddField(
            model_name='trip',
            name='adults',
            field=models.IntegerField(default=0, verbose_name='Взрослых в группе'),
        ),
        migrations.AddField(
            model_name='trip',
            name='kids',
            field=models.IntegerField(default=0, verbose_name='Детей в группе'),
        ),
    ]
