# Generated by Django 3.1.6 on 2021-02-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_auto_20210227_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_checked',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Модерация проведена'),
        ),
    ]
