# Generated by Django 3.1.6 on 2021-02-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_auto_20210208_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Инструктор доступен для маршрута'),
        ),
    ]
