# Generated by Django 3.1.6 on 2021-03-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_auto_20210302_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='type',
            field=models.IntegerField(choices=[(1, 'Пеший'), (2, 'Велосипедный'), (3, 'Водный')], db_index=True, default=1, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='ends_at',
            field=models.DateTimeField(db_index=True, verbose_name='Время окончания похода'),
        ),
    ]
