# Generated by Django 3.1.6 on 2021-02-16 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
        ('travelapp', '0008_auto_20210216_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='userapp.instructor'),
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Traveler',
        ),
        migrations.AddField(
            model_name='trip',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='userapp.instructor'),
        ),
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='travelapp.route'),
        ),
    ]
