# Generated by Django 3.1.6 on 2021-02-18 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0010_auto_20210218_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='group_size',
            field=models.IntegerField(null=True, verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='route',
            name='featured_photo',
            field=models.ImageField(blank=True, upload_to='static/img', verbose_name='Фото для оформления маршрута'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='travelapp.route'),
        ),
    ]
