# Generated by Django 3.1.6 on 2021-02-26 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0020_district_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travelapp.region', verbose_name='Местоположение'),
        ),
    ]
