# Generated by Django 3.1.6 on 2021-02-27 12:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210226_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='activation_key_expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 12, 48, 52, 972646, tzinfo=utc), verbose_name='Крайний срок текущей активации'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='static/user_pics'),
        ),
    ]
