# Generated by Django 3.1.6 on 2021-02-27 15:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20210227_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='activation_key_expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 15, 22, 56, 674788, tzinfo=utc), verbose_name='Крайний срок текущей активации'),
        ),
    ]
