# Generated by Django 3.1.6 on 2021-02-25 10:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20210222_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_traveler',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='activation_key_expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 10, 44, 1, 224028, tzinfo=utc), verbose_name='Крайний срок текущей активации'),
        ),
    ]
