# Generated by Django 3.1.6 on 2021-03-04 15:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_auto_20210302_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='activation_key_expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 15, 11, 52, 667132, tzinfo=utc), verbose_name='Крайний срок текущей активации'),
        ),
    ]
