# Generated by Django 3.1.6 on 2021-02-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travelapp', '0008_auto_20210216_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО инструктора')),
                ('about', models.TextField(blank=True, verbose_name='О себе')),
                ('home_region', models.CharField(blank=True, max_length=100, verbose_name='Место проживания')),
                ('routes_run', models.IntegerField(default=0, verbose_name='Пройдено маршрутов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Инструктор доступен для маршрута')),
            ],
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО пользователя')),
                ('about', models.TextField(blank=True, verbose_name='О себе')),
                ('home_region', models.CharField(max_length=100, verbose_name='Место проживания')),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='userapp.Instructor', verbose_name='Подписки')),
                ('trips_completed', models.ManyToManyField(related_name='participants', to='travelapp.Trip', verbose_name='Походы')),
            ],
        ),
    ]
