# Generated by Django 3.1.6 on 2021-02-21 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0016_auto_20210221_1616'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveler',
            name='following',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='trips_completed',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Traveler',
        ),
    ]
