# Generated by Django 3.1.6 on 2021-02-26 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_auto_20210226_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='activation_key_expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 17, 16, 29, 367266, tzinfo=utc), verbose_name='Крайний срок текущей активации'),
        ),
    ]
