# Generated by Django 3.1.6 on 2021-02-22 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0017_auto_20210222_1249'),
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='group_size',
            field=models.IntegerField(default=1, verbose_name='Размер вашей группы'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered', to='travelapp.trip'),
        ),
    ]
