# Generated by Django 3.1.6 on 2021-02-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0017_auto_20210222_1249'),
        ('ordersapp', '0002_auto_20210222_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='options_used',
            field=models.ManyToManyField(to='travelapp.TripOptionAvailable'),
        ),
    ]
