# Generated by Django 3.1.6 on 2021-02-22 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0017_auto_20210222_1249'),
        ('ordersapp', '0003_orderitem_options_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='options_used',
            field=models.ManyToManyField(to='travelapp.TripOptionAvailable', verbose_name='Дополнительные опции'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered', to='travelapp.trip', verbose_name='Поход'),
        ),
    ]
