# Generated by Django 3.1.6 on 2021-03-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Не удалён'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_allowed',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Прошёл модерацию'),
        ),
    ]
