# Generated by Django 3.1.6 on 2021-03-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_auto_20210304_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='commentphoto',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено'),
        ),
    ]
